# trigger on main push
trigger:
  branches:
    include:
    - main

pr:
  branches:
    include:
    - '*'

pool:
  vmImage: ubuntu-latest

variables:
  appDir: fakebook

stages:
- stage: analyze
  jobs:
  - job: build
    steps:
    - task: NodeTool@0
      displayName: install nodejs
      inputs:
        versionSpec: '14.x'

    - script: npm ci
      displayName: npm install
      workingDirectory: $(appDir)

    - script: npx ng build --prod
      displayName: ng build
      workingDirectory: $(appDir)

    - script: npx ng lint
      displayName: ng lint
      workingDirectory: $(appDir)

    - task: SonarCloudPrepare@1
      displayName: sonar prepare analysis
      inputs:
        SonarCloud: 'SonarCloud Token'
        organization: '2011-fakebook-project3'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: '2011-fakebook-project3_ng'
        cliProjectName: 'ng'
        cliSources: '$(appDir)/src'
        extraProperties: |
          sonar.coverage.exclusions=$(appDir)/src/**/*.spec.ts
          sonar.javascript.lcov.reportPaths=$(appDir)/coverage/$(appDir)/lcov.info

    # if previous steps successful, exactly one of these two steps should run:
    # test on main or PRs to main
    - script: npx ng test --browsers ChromeHeadless --watch=false --code-coverage
      displayName: ng test (failures disallowed)
      condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['System.PullRequest.TargetBranch'], 'main')))
      workingDirectory: $(appDir)

    # test outside of main or PRs to main
    # (identical except: fails allowed for TDD workflow)
    - script: npx ng test --browsers ChromeHeadless --watch=false --code-coverage
      displayName: ng test (failures allowed)
      condition: and(succeeded(), not(or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['System.PullRequest.TargetBranch'], 'main'))))
      continueOnError: true
      workingDirectory: $(appDir)

    - task: SonarCloudAnalyze@1
      displayName: sonar run analysis
      condition: always()

    - task: SonarCloudPublish@1
      displayName: sonar analysis publish
      condition: always()
      inputs:
        pollingTimeoutSec: '300'

- stage: docker
  variables:
    imageName: fakebookng
  jobs:
  - job: build
    condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/main'))
    steps:
    - task: Docker@2
      displayName: docker build app image
      inputs:
        repository: '$(imageName)'
        command: 'build'
        Dockerfile: '$(appDir)/Dockerfile'
  - job: build_push
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    steps:
    - publish: .kubernetes
      displayName: publish artifact k8s
      artifact: k8s
    - task: Docker@2
      displayName: docker build-push app image
      inputs:
        containerRegistry: 'fakebook-acr'
        repository: '$(imageName)'
        command: 'buildAndPush'
        Dockerfile: '$(appDir)/Dockerfile'
        tags: |
          latest
          $(Build.BuildNumber)

- stage: deploy
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - deployment: production
    environment: production
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: kubectl apply
            inputs:
              action: 'deploy'
              kubernetesServiceConnection: 'production-fakebook-default-1610381990554'
              namespace: 'default'
              manifests: '$(Pipeline.Workspace)/k8s/**/*'

          - task: Kubernetes@1
            displayName: kubectl rollout restart
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceEndpoint: 'production-fakebook-default-1610381990554'
              namespace: 'default'
              command: 'rollout'
              useConfigurationFile: true
              configuration: '$(Pipeline.Workspace)/k8s/kubernetes_deployments.yaml'
              arguments: 'restart'
              secretType: 'dockerRegistry'
              containerRegistryType: 'Azure Container Registry'
