# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
variables:
  appDir: 'fakebook/'

trigger:
  branches:
   include: 
     - main
  paths:
    include:
      - az-pipeline-angular.yml

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  continueOnError: True
  displayName: 'npm install and build'
  workingDirectory: $(appDir)

- task: SonarCloudPrepare@1
  continueOnError: True
  displayName: 'sonarcloud prepare'
  inputs:
    SonarCloud: 'SonarCloud Token'
    organization: '2011-fakebook-project3'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: '2011-fakebook-project3_ng'
    cliProjectName: 'ng'
    cliSources: '$(appDir)/src'

- task: SonarCloudAnalyze@1
  continueOnError: True
  displayName: 'sonarcloud analyze'

- task: SonarCloudPublish@1
  continueOnError: True
  displayName: 'sonarcloud publish'
  inputs:
    pollingTimeoutSec: '300'

