# trigger on main push
trigger:
  branches:
    include:
    - dev
  paths:
    include:
    - azure-pipelines.yml
    - fakebook

pr:
  branches:
    include:
    - '*'
  paths:
    include:
    - azure-pipelines.yml
    - fakebook

pool:
  vmImage: ubuntu-latest

variables:
  appDir: fakebook

stages:
- stage: analyze
  jobs:
  - job: build
    steps:
    # using node version 15.x to enforce npm 7.x
    - task: NodeTool@0
      displayName: install nodejs
      inputs:
        versionSpec: '15.x'

    - script: npm ci
      displayName: npm install
      workingDirectory: $(appDir)

    - script: npx ng build --prod
      displayName: ng build
      workingDirectory: $(appDir)
    
    - task: AzureRmWebAppDeployment@4
      displayName: azure app service deploy
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure subscription 1(2)(b039e9a7-436a-45e5-9c21-b3c078fecd2c)'
        appType: 'webApp'
        WebAppName: '2011-Revature-Fakebook'
        packageForLinux: '$(appDir)/dist/$(appDir)'